package com.sjec.rcms.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.sjec.rcms.dao.EntityAssistWorker;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_ASSIST_WORKER.
*/
public class EntityAssistWorkerDao extends AbstractDao<EntityAssistWorker, Void> {

    public static final String TABLENAME = "ENTITY_ASSIST_WORKER";

    /**
     * Properties of entity EntityAssistWorker.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property UserID = new Property(0, String.class, "UserID", false, "USER_ID");
        public final static Property AssistStatus = new Property(1, Integer.class, "AssistStatus", false, "ASSIST_STATUS");
        public final static Property StaffNo = new Property(2, String.class, "StaffNo", false, "STAFF_NO");
        public final static Property Name = new Property(3, String.class, "Name", false, "NAME");
        public final static Property Telephone = new Property(4, String.class, "Telephone", false, "TELEPHONE");
    };


    public EntityAssistWorkerDao(DaoConfig config) {
        super(config);
    }
    
    public EntityAssistWorkerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_ASSIST_WORKER' (" + //
                "'USER_ID' TEXT," + // 0: UserID
                "'ASSIST_STATUS' INTEGER," + // 1: AssistStatus
                "'STAFF_NO' TEXT," + // 2: StaffNo
                "'NAME' TEXT," + // 3: Name
                "'TELEPHONE' TEXT);"); // 4: Telephone
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_ASSIST_WORKER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityAssistWorker entity) {
        stmt.clearBindings();
 
        String UserID = entity.getUserID();
        if (UserID != null) {
            stmt.bindString(1, UserID);
        }
 
        Integer AssistStatus = entity.getAssistStatus();
        if (AssistStatus != null) {
            stmt.bindLong(2, AssistStatus);
        }
 
        String StaffNo = entity.getStaffNo();
        if (StaffNo != null) {
            stmt.bindString(3, StaffNo);
        }
 
        String Name = entity.getName();
        if (Name != null) {
            stmt.bindString(4, Name);
        }
 
        String Telephone = entity.getTelephone();
        if (Telephone != null) {
            stmt.bindString(5, Telephone);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntityAssistWorker readEntity(Cursor cursor, int offset) {
        EntityAssistWorker entity = new EntityAssistWorker( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // UserID
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // AssistStatus
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // StaffNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // Telephone
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityAssistWorker entity, int offset) {
        entity.setUserID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAssistStatus(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setStaffNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTelephone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntityAssistWorker entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntityAssistWorker entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
