package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_USER_COMPANY.
 */
public class EntityUserCompany {

    public String InnerID;
    public String CompanyCode;
    public String CompanyName;

    public EntityUserCompany() {
    }

    public EntityUserCompany(String InnerID, String CompanyCode, String CompanyName) {
        this.InnerID = InnerID;
        this.CompanyCode = CompanyCode;
        this.CompanyName = CompanyName;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getCompanyCode() {
        return CompanyCode;
    }

    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getCompanyName() {
        return CompanyName;
    }

    public void setCompanyName(String CompanyName) {
        this.CompanyName = CompanyName;
    }

}
