package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_WORK_ORDER_PIC.
 */
public class EntityWorkOrderPic {

    public Integer InnerID;
    public String WorkorderID;
    public String PicPath;
    public String Add_UserID;
    public Integer Add_Time;
    public Integer Add_IP;

    public EntityWorkOrderPic() {
    }

    public EntityWorkOrderPic(Integer InnerID, String WorkorderID, String PicPath, String Add_UserID, Integer Add_Time, Integer Add_IP) {
        this.InnerID = InnerID;
        this.WorkorderID = WorkorderID;
        this.PicPath = PicPath;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.Add_IP = Add_IP;
    }

    public Integer getInnerID() {
        return InnerID;
    }

    public void setInnerID(Integer InnerID) {
        this.InnerID = InnerID;
    }

    public String getWorkorderID() {
        return WorkorderID;
    }

    public void setWorkorderID(String WorkorderID) {
        this.WorkorderID = WorkorderID;
    }

    public String getPicPath() {
        return PicPath;
    }

    public void setPicPath(String PicPath) {
        this.PicPath = PicPath;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public Integer getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(Integer Add_Time) {
        this.Add_Time = Add_Time;
    }

    public Integer getAdd_IP() {
        return Add_IP;
    }

    public void setAdd_IP(Integer Add_IP) {
        this.Add_IP = Add_IP;
    }

}
