package com.sjec.rcms.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.sjec.rcms.dao.EntityKnowledgeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ENTITY_KNOWLEDGE_TYPE.
*/
public class EntityKnowledgeTypeDao extends AbstractDao<EntityKnowledgeType, Void> {

    public static final String TABLENAME = "ENTITY_KNOWLEDGE_TYPE";

    /**
     * Properties of entity EntityKnowledgeType.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property InnerID = new Property(0, String.class, "InnerID", false, "INNER_ID");
        public final static Property ClassCode = new Property(1, String.class, "ClassCode", false, "CLASS_CODE");
        public final static Property ClassName = new Property(2, String.class, "ClassName", false, "CLASS_NAME");
        public final static Property Tag = new Property(3, String.class, "Tag", false, "TAG");
    };


    public EntityKnowledgeTypeDao(DaoConfig config) {
        super(config);
    }
    
    public EntityKnowledgeTypeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ENTITY_KNOWLEDGE_TYPE' (" + //
                "'INNER_ID' TEXT," + // 0: InnerID
                "'CLASS_CODE' TEXT," + // 1: ClassCode
                "'CLASS_NAME' TEXT," + // 2: ClassName
                "'TAG' TEXT);"); // 3: Tag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ENTITY_KNOWLEDGE_TYPE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EntityKnowledgeType entity) {
        stmt.clearBindings();
 
        String InnerID = entity.getInnerID();
        if (InnerID != null) {
            stmt.bindString(1, InnerID);
        }
 
        String ClassCode = entity.getClassCode();
        if (ClassCode != null) {
            stmt.bindString(2, ClassCode);
        }
 
        String ClassName = entity.getClassName();
        if (ClassName != null) {
            stmt.bindString(3, ClassName);
        }
 
        String Tag = entity.getTag();
        if (Tag != null) {
            stmt.bindString(4, Tag);
        }
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public EntityKnowledgeType readEntity(Cursor cursor, int offset) {
        EntityKnowledgeType entity = new EntityKnowledgeType( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // InnerID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ClassCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // ClassName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // Tag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EntityKnowledgeType entity, int offset) {
        entity.setInnerID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setClassCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setClassName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTag(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(EntityKnowledgeType entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(EntityKnowledgeType entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
