package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_PAUSE_CONFIRM.
 */
public class EntityPauseConfirm {

    public String InnerID;
    public String WorkorderID;
    public String OccurTime;
    public String UserID;
    public Integer FromPauseStatus;
    public Integer TargetPauseStatus;
    public Integer AdminCheck;
    public String CheckTime;
    public String Remark;
    public String Device_Num;
    public String ChargeUserName;
    public String StartTime;
    public String Village_Name;
    public String Workorder_Remark;

    public EntityPauseConfirm() {
    }

    public EntityPauseConfirm(String InnerID, String WorkorderID, String OccurTime, String UserID, Integer FromPauseStatus, Integer TargetPauseStatus, Integer AdminCheck, String CheckTime, String Remark, String Device_Num, String ChargeUserName, String StartTime, String Village_Name, String Workorder_Remark) {
        this.InnerID = InnerID;
        this.WorkorderID = WorkorderID;
        this.OccurTime = OccurTime;
        this.UserID = UserID;
        this.FromPauseStatus = FromPauseStatus;
        this.TargetPauseStatus = TargetPauseStatus;
        this.AdminCheck = AdminCheck;
        this.CheckTime = CheckTime;
        this.Remark = Remark;
        this.Device_Num = Device_Num;
        this.ChargeUserName = ChargeUserName;
        this.StartTime = StartTime;
        this.Village_Name = Village_Name;
        this.Workorder_Remark = Workorder_Remark;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getWorkorderID() {
        return WorkorderID;
    }

    public void setWorkorderID(String WorkorderID) {
        this.WorkorderID = WorkorderID;
    }

    public String getOccurTime() {
        return OccurTime;
    }

    public void setOccurTime(String OccurTime) {
        this.OccurTime = OccurTime;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public Integer getFromPauseStatus() {
        return FromPauseStatus;
    }

    public void setFromPauseStatus(Integer FromPauseStatus) {
        this.FromPauseStatus = FromPauseStatus;
    }

    public Integer getTargetPauseStatus() {
        return TargetPauseStatus;
    }

    public void setTargetPauseStatus(Integer TargetPauseStatus) {
        this.TargetPauseStatus = TargetPauseStatus;
    }

    public Integer getAdminCheck() {
        return AdminCheck;
    }

    public void setAdminCheck(Integer AdminCheck) {
        this.AdminCheck = AdminCheck;
    }

    public String getCheckTime() {
        return CheckTime;
    }

    public void setCheckTime(String CheckTime) {
        this.CheckTime = CheckTime;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getDevice_Num() {
        return Device_Num;
    }

    public void setDevice_Num(String Device_Num) {
        this.Device_Num = Device_Num;
    }

    public String getChargeUserName() {
        return ChargeUserName;
    }

    public void setChargeUserName(String ChargeUserName) {
        this.ChargeUserName = ChargeUserName;
    }

    public String getStartTime() {
        return StartTime;
    }

    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    public String getVillage_Name() {
        return Village_Name;
    }

    public void setVillage_Name(String Village_Name) {
        this.Village_Name = Village_Name;
    }

    public String getWorkorder_Remark() {
        return Workorder_Remark;
    }

    public void setWorkorder_Remark(String Workorder_Remark) {
        this.Workorder_Remark = Workorder_Remark;
    }

}
