package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_REPAIR.
 */
public class EntityRepair {

    public String InnerID;
    public String Company_Num;
    public String Device_Num;
    public String Error_Info;
    public String Error_Detail;
    public Integer Status;
    public Integer StartFlag;
    public String StartTime;
    public Integer EndFlag;
    public String EndTime;
    public String StartLongitude;
    public String StartLatitude;
    public String EndLongitude	;
    public String EndLatitude;
    public String RepairDesc;
    public String LeaderRemark;
    public String Validate;
    public String Add_UserID;
    public String Add_Time;
    public String Add_IP;
    public String Update_UserID;
    public String Update_Time;
    public String Update_IP	;
    public String ChargeUserID;

    public EntityRepair() {
    }

    public EntityRepair(String InnerID, String Company_Num, String Device_Num, String Error_Info, String Error_Detail, Integer Status, Integer StartFlag, String StartTime, Integer EndFlag, String EndTime, String StartLongitude, String StartLatitude, String EndLongitude	, String EndLatitude, String RepairDesc, String LeaderRemark, String Validate, String Add_UserID, String Add_Time, String Add_IP, String Update_UserID, String Update_Time, String Update_IP	, String ChargeUserID) {
        this.InnerID = InnerID;
        this.Company_Num = Company_Num;
        this.Device_Num = Device_Num;
        this.Error_Info = Error_Info;
        this.Error_Detail = Error_Detail;
        this.Status = Status;
        this.StartFlag = StartFlag;
        this.StartTime = StartTime;
        this.EndFlag = EndFlag;
        this.EndTime = EndTime;
        this.StartLongitude = StartLongitude;
        this.StartLatitude = StartLatitude;
        this.EndLongitude	 = EndLongitude	;
        this.EndLatitude = EndLatitude;
        this.RepairDesc = RepairDesc;
        this.LeaderRemark = LeaderRemark;
        this.Validate = Validate;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.Add_IP = Add_IP;
        this.Update_UserID = Update_UserID;
        this.Update_Time = Update_Time;
        this.Update_IP	 = Update_IP	;
        this.ChargeUserID = ChargeUserID;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getCompany_Num() {
        return Company_Num;
    }

    public void setCompany_Num(String Company_Num) {
        this.Company_Num = Company_Num;
    }

    public String getDevice_Num() {
        return Device_Num;
    }

    public void setDevice_Num(String Device_Num) {
        this.Device_Num = Device_Num;
    }

    public String getError_Info() {
        return Error_Info;
    }

    public void setError_Info(String Error_Info) {
        this.Error_Info = Error_Info;
    }

    public String getError_Detail() {
        return Error_Detail;
    }

    public void setError_Detail(String Error_Detail) {
        this.Error_Detail = Error_Detail;
    }

    public Integer getStatus() {
        return Status;
    }

    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public Integer getStartFlag() {
        return StartFlag;
    }

    public void setStartFlag(Integer StartFlag) {
        this.StartFlag = StartFlag;
    }

    public String getStartTime() {
        return StartTime;
    }

    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    public Integer getEndFlag() {
        return EndFlag;
    }

    public void setEndFlag(Integer EndFlag) {
        this.EndFlag = EndFlag;
    }

    public String getEndTime() {
        return EndTime;
    }

    public void setEndTime(String EndTime) {
        this.EndTime = EndTime;
    }

    public String getStartLongitude() {
        return StartLongitude;
    }

    public void setStartLongitude(String StartLongitude) {
        this.StartLongitude = StartLongitude;
    }

    public String getStartLatitude() {
        return StartLatitude;
    }

    public void setStartLatitude(String StartLatitude) {
        this.StartLatitude = StartLatitude;
    }

    public String getEndLongitude	() {
        return EndLongitude	;
    }

    public void setEndLongitude	(String EndLongitude	) {
        this.EndLongitude	 = EndLongitude	;
    }

    public String getEndLatitude() {
        return EndLatitude;
    }

    public void setEndLatitude(String EndLatitude) {
        this.EndLatitude = EndLatitude;
    }

    public String getRepairDesc() {
        return RepairDesc;
    }

    public void setRepairDesc(String RepairDesc) {
        this.RepairDesc = RepairDesc;
    }

    public String getLeaderRemark() {
        return LeaderRemark;
    }

    public void setLeaderRemark(String LeaderRemark) {
        this.LeaderRemark = LeaderRemark;
    }

    public String getValidate() {
        return Validate;
    }

    public void setValidate(String Validate) {
        this.Validate = Validate;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getAdd_IP() {
        return Add_IP;
    }

    public void setAdd_IP(String Add_IP) {
        this.Add_IP = Add_IP;
    }

    public String getUpdate_UserID() {
        return Update_UserID;
    }

    public void setUpdate_UserID(String Update_UserID) {
        this.Update_UserID = Update_UserID;
    }

    public String getUpdate_Time() {
        return Update_Time;
    }

    public void setUpdate_Time(String Update_Time) {
        this.Update_Time = Update_Time;
    }

    public String getUpdate_IP	() {
        return Update_IP	;
    }

    public void setUpdate_IP	(String Update_IP	) {
        this.Update_IP	 = Update_IP	;
    }

    public String getChargeUserID() {
        return ChargeUserID;
    }

    public void setChargeUserID(String ChargeUserID) {
        this.ChargeUserID = ChargeUserID;
    }

}
