package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_SPARE_PART_QUOTATION.
 */
public class EntitySparePartQuotation {

    public Integer ID;
    public String Owner;
    public String Quotation_Name;
    public String Status;
    public String Quotation_Type;
    public String Creator;
    public String CreateTime;
    public String CreateIP;
    public String Updater;
    public String UpdateTime;
    public String UpdateIP;
    public String Version_Code;
    public String Check_Status;
    public String Billing_Status;
    public String Proceeds_Status;
    public String Total_Amount;
    public String Total_Amount_Discount;
    public String Discount;
    public String SourceType;
    public String Person_Amount;
    public String Delivery_Amount;
    public String Check_Amount;
    public String CompanyType;
    public String Source;
    public String CompanyID;
    public String BigCustomer_ID;
    public String OrderNum;
    public String MaintenanceType;
    public String Use_Status;
    public String DeviceNo;
    public String ProgramName;

    public EntitySparePartQuotation() {
    }

    public EntitySparePartQuotation(Integer ID, String Owner, String Quotation_Name, String Status, String Quotation_Type, String Creator, String CreateTime, String CreateIP, String Updater, String UpdateTime, String UpdateIP, String Version_Code, String Check_Status, String Billing_Status, String Proceeds_Status, String Total_Amount, String Total_Amount_Discount, String Discount, String SourceType, String Person_Amount, String Delivery_Amount, String Check_Amount, String CompanyType, String Source, String CompanyID, String BigCustomer_ID, String OrderNum, String MaintenanceType, String Use_Status, String DeviceNo, String ProgramName) {
        this.ID = ID;
        this.Owner = Owner;
        this.Quotation_Name = Quotation_Name;
        this.Status = Status;
        this.Quotation_Type = Quotation_Type;
        this.Creator = Creator;
        this.CreateTime = CreateTime;
        this.CreateIP = CreateIP;
        this.Updater = Updater;
        this.UpdateTime = UpdateTime;
        this.UpdateIP = UpdateIP;
        this.Version_Code = Version_Code;
        this.Check_Status = Check_Status;
        this.Billing_Status = Billing_Status;
        this.Proceeds_Status = Proceeds_Status;
        this.Total_Amount = Total_Amount;
        this.Total_Amount_Discount = Total_Amount_Discount;
        this.Discount = Discount;
        this.SourceType = SourceType;
        this.Person_Amount = Person_Amount;
        this.Delivery_Amount = Delivery_Amount;
        this.Check_Amount = Check_Amount;
        this.CompanyType = CompanyType;
        this.Source = Source;
        this.CompanyID = CompanyID;
        this.BigCustomer_ID = BigCustomer_ID;
        this.OrderNum = OrderNum;
        this.MaintenanceType = MaintenanceType;
        this.Use_Status = Use_Status;
        this.DeviceNo = DeviceNo;
        this.ProgramName = ProgramName;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public String getOwner() {
        return Owner;
    }

    public void setOwner(String Owner) {
        this.Owner = Owner;
    }

    public String getQuotation_Name() {
        return Quotation_Name;
    }

    public void setQuotation_Name(String Quotation_Name) {
        this.Quotation_Name = Quotation_Name;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getQuotation_Type() {
        return Quotation_Type;
    }

    public void setQuotation_Type(String Quotation_Type) {
        this.Quotation_Type = Quotation_Type;
    }

    public String getCreator() {
        return Creator;
    }

    public void setCreator(String Creator) {
        this.Creator = Creator;
    }

    public String getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    public String getCreateIP() {
        return CreateIP;
    }

    public void setCreateIP(String CreateIP) {
        this.CreateIP = CreateIP;
    }

    public String getUpdater() {
        return Updater;
    }

    public void setUpdater(String Updater) {
        this.Updater = Updater;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

    public String getUpdateIP() {
        return UpdateIP;
    }

    public void setUpdateIP(String UpdateIP) {
        this.UpdateIP = UpdateIP;
    }

    public String getVersion_Code() {
        return Version_Code;
    }

    public void setVersion_Code(String Version_Code) {
        this.Version_Code = Version_Code;
    }

    public String getCheck_Status() {
        return Check_Status;
    }

    public void setCheck_Status(String Check_Status) {
        this.Check_Status = Check_Status;
    }

    public String getBilling_Status() {
        return Billing_Status;
    }

    public void setBilling_Status(String Billing_Status) {
        this.Billing_Status = Billing_Status;
    }

    public String getProceeds_Status() {
        return Proceeds_Status;
    }

    public void setProceeds_Status(String Proceeds_Status) {
        this.Proceeds_Status = Proceeds_Status;
    }

    public String getTotal_Amount() {
        return Total_Amount;
    }

    public void setTotal_Amount(String Total_Amount) {
        this.Total_Amount = Total_Amount;
    }

    public String getTotal_Amount_Discount() {
        return Total_Amount_Discount;
    }

    public void setTotal_Amount_Discount(String Total_Amount_Discount) {
        this.Total_Amount_Discount = Total_Amount_Discount;
    }

    public String getDiscount() {
        return Discount;
    }

    public void setDiscount(String Discount) {
        this.Discount = Discount;
    }

    public String getSourceType() {
        return SourceType;
    }

    public void setSourceType(String SourceType) {
        this.SourceType = SourceType;
    }

    public String getPerson_Amount() {
        return Person_Amount;
    }

    public void setPerson_Amount(String Person_Amount) {
        this.Person_Amount = Person_Amount;
    }

    public String getDelivery_Amount() {
        return Delivery_Amount;
    }

    public void setDelivery_Amount(String Delivery_Amount) {
        this.Delivery_Amount = Delivery_Amount;
    }

    public String getCheck_Amount() {
        return Check_Amount;
    }

    public void setCheck_Amount(String Check_Amount) {
        this.Check_Amount = Check_Amount;
    }

    public String getCompanyType() {
        return CompanyType;
    }

    public void setCompanyType(String CompanyType) {
        this.CompanyType = CompanyType;
    }

    public String getSource() {
        return Source;
    }

    public void setSource(String Source) {
        this.Source = Source;
    }

    public String getCompanyID() {
        return CompanyID;
    }

    public void setCompanyID(String CompanyID) {
        this.CompanyID = CompanyID;
    }

    public String getBigCustomer_ID() {
        return BigCustomer_ID;
    }

    public void setBigCustomer_ID(String BigCustomer_ID) {
        this.BigCustomer_ID = BigCustomer_ID;
    }

    public String getOrderNum() {
        return OrderNum;
    }

    public void setOrderNum(String OrderNum) {
        this.OrderNum = OrderNum;
    }

    public String getMaintenanceType() {
        return MaintenanceType;
    }

    public void setMaintenanceType(String MaintenanceType) {
        this.MaintenanceType = MaintenanceType;
    }

    public String getUse_Status() {
        return Use_Status;
    }

    public void setUse_Status(String Use_Status) {
        this.Use_Status = Use_Status;
    }

    public String getDeviceNo() {
        return DeviceNo;
    }

    public void setDeviceNo(String DeviceNo) {
        this.DeviceNo = DeviceNo;
    }

    public String getProgramName() {
        return ProgramName;
    }

    public void setProgramName(String ProgramName) {
        this.ProgramName = ProgramName;
    }

}
