package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_USER.
 */
public class EntityUser {

    public String InnerID;
    public String UserID;
    public String UserName;
    public String Password;
    public String Telephone;
    public String Email;
    public String Description;
    public String NavigationUrl;
    public String CityID;

    public EntityUser() {
    }

    public EntityUser(String InnerID, String UserID, String UserName, String Password, String Telephone, String Email, String Description, String NavigationUrl, String CityID) {
        this.InnerID = InnerID;
        this.UserID = UserID;
        this.UserName = UserName;
        this.Password = Password;
        this.Telephone = Telephone;
        this.Email = Email;
        this.Description = Description;
        this.NavigationUrl = NavigationUrl;
        this.CityID = CityID;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getPassword() {
        return Password;
    }

    public void setPassword(String Password) {
        this.Password = Password;
    }

    public String getTelephone() {
        return Telephone;
    }

    public void setTelephone(String Telephone) {
        this.Telephone = Telephone;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getNavigationUrl() {
        return NavigationUrl;
    }

    public void setNavigationUrl(String NavigationUrl) {
        this.NavigationUrl = NavigationUrl;
    }

    public String getCityID() {
        return CityID;
    }

    public void setCityID(String CityID) {
        this.CityID = CityID;
    }

}
