package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_SPARE_PART_QUOTATION_DATA.
 */
public class EntitySparePartQuotationData {

    public Integer ID;
    public String Quotation_ID;
    public String Owner;
    public String Status;
    public String Data_ID;
    public String Data_Type;
    public String Draw_Code;
    public String Product_Code;
    public String Code;
    public String FakeCode;
    public String Name;
    public String SPCF;
    public String Unit;
    public String Use_Status;
    public String Purchase_Price;
    public String Make_Model;
    public String Make_Company;
    public String Weight;
    public String Size;
    public String Delivery_Period;
    public String Remark;
    public String Finance_Price;
    public String Discount;
    public String Discount_Price;
    public String Quantity;
    public String Total_Price;
    public String Creator;
    public String CreateTime;
    public String CreateIP;
    public String Updater;
    public String UpdateTime;
    public String UpdateIP;
    public String DeliveryTime;
    public String SetupTime;

    public EntitySparePartQuotationData() {
    }

    public EntitySparePartQuotationData(Integer ID, String Quotation_ID, String Owner, String Status, String Data_ID, String Data_Type, String Draw_Code, String Product_Code, String Code, String FakeCode, String Name, String SPCF, String Unit, String Use_Status, String Purchase_Price, String Make_Model, String Make_Company, String Weight, String Size, String Delivery_Period, String Remark, String Finance_Price, String Discount, String Discount_Price, String Quantity, String Total_Price, String Creator, String CreateTime, String CreateIP, String Updater, String UpdateTime, String UpdateIP, String DeliveryTime, String SetupTime) {
        this.ID = ID;
        this.Quotation_ID = Quotation_ID;
        this.Owner = Owner;
        this.Status = Status;
        this.Data_ID = Data_ID;
        this.Data_Type = Data_Type;
        this.Draw_Code = Draw_Code;
        this.Product_Code = Product_Code;
        this.Code = Code;
        this.FakeCode = FakeCode;
        this.Name = Name;
        this.SPCF = SPCF;
        this.Unit = Unit;
        this.Use_Status = Use_Status;
        this.Purchase_Price = Purchase_Price;
        this.Make_Model = Make_Model;
        this.Make_Company = Make_Company;
        this.Weight = Weight;
        this.Size = Size;
        this.Delivery_Period = Delivery_Period;
        this.Remark = Remark;
        this.Finance_Price = Finance_Price;
        this.Discount = Discount;
        this.Discount_Price = Discount_Price;
        this.Quantity = Quantity;
        this.Total_Price = Total_Price;
        this.Creator = Creator;
        this.CreateTime = CreateTime;
        this.CreateIP = CreateIP;
        this.Updater = Updater;
        this.UpdateTime = UpdateTime;
        this.UpdateIP = UpdateIP;
        this.DeliveryTime = DeliveryTime;
        this.SetupTime = SetupTime;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public String getQuotation_ID() {
        return Quotation_ID;
    }

    public void setQuotation_ID(String Quotation_ID) {
        this.Quotation_ID = Quotation_ID;
    }

    public String getOwner() {
        return Owner;
    }

    public void setOwner(String Owner) {
        this.Owner = Owner;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getData_ID() {
        return Data_ID;
    }

    public void setData_ID(String Data_ID) {
        this.Data_ID = Data_ID;
    }

    public String getData_Type() {
        return Data_Type;
    }

    public void setData_Type(String Data_Type) {
        this.Data_Type = Data_Type;
    }

    public String getDraw_Code() {
        return Draw_Code;
    }

    public void setDraw_Code(String Draw_Code) {
        this.Draw_Code = Draw_Code;
    }

    public String getProduct_Code() {
        return Product_Code;
    }

    public void setProduct_Code(String Product_Code) {
        this.Product_Code = Product_Code;
    }

    public String getCode() {
        return Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    public String getFakeCode() {
        return FakeCode;
    }

    public void setFakeCode(String FakeCode) {
        this.FakeCode = FakeCode;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getSPCF() {
        return SPCF;
    }

    public void setSPCF(String SPCF) {
        this.SPCF = SPCF;
    }

    public String getUnit() {
        return Unit;
    }

    public void setUnit(String Unit) {
        this.Unit = Unit;
    }

    public String getUse_Status() {
        return Use_Status;
    }

    public void setUse_Status(String Use_Status) {
        this.Use_Status = Use_Status;
    }

    public String getPurchase_Price() {
        return Purchase_Price;
    }

    public void setPurchase_Price(String Purchase_Price) {
        this.Purchase_Price = Purchase_Price;
    }

    public String getMake_Model() {
        return Make_Model;
    }

    public void setMake_Model(String Make_Model) {
        this.Make_Model = Make_Model;
    }

    public String getMake_Company() {
        return Make_Company;
    }

    public void setMake_Company(String Make_Company) {
        this.Make_Company = Make_Company;
    }

    public String getWeight() {
        return Weight;
    }

    public void setWeight(String Weight) {
        this.Weight = Weight;
    }

    public String getSize() {
        return Size;
    }

    public void setSize(String Size) {
        this.Size = Size;
    }

    public String getDelivery_Period() {
        return Delivery_Period;
    }

    public void setDelivery_Period(String Delivery_Period) {
        this.Delivery_Period = Delivery_Period;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getFinance_Price() {
        return Finance_Price;
    }

    public void setFinance_Price(String Finance_Price) {
        this.Finance_Price = Finance_Price;
    }

    public String getDiscount() {
        return Discount;
    }

    public void setDiscount(String Discount) {
        this.Discount = Discount;
    }

    public String getDiscount_Price() {
        return Discount_Price;
    }

    public void setDiscount_Price(String Discount_Price) {
        this.Discount_Price = Discount_Price;
    }

    public String getQuantity() {
        return Quantity;
    }

    public void setQuantity(String Quantity) {
        this.Quantity = Quantity;
    }

    public String getTotal_Price() {
        return Total_Price;
    }

    public void setTotal_Price(String Total_Price) {
        this.Total_Price = Total_Price;
    }

    public String getCreator() {
        return Creator;
    }

    public void setCreator(String Creator) {
        this.Creator = Creator;
    }

    public String getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    public String getCreateIP() {
        return CreateIP;
    }

    public void setCreateIP(String CreateIP) {
        this.CreateIP = CreateIP;
    }

    public String getUpdater() {
        return Updater;
    }

    public void setUpdater(String Updater) {
        this.Updater = Updater;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

    public String getUpdateIP() {
        return UpdateIP;
    }

    public void setUpdateIP(String UpdateIP) {
        this.UpdateIP = UpdateIP;
    }

    public String getDeliveryTime() {
        return DeliveryTime;
    }

    public void setDeliveryTime(String DeliveryTime) {
        this.DeliveryTime = DeliveryTime;
    }

    public String getSetupTime() {
        return SetupTime;
    }

    public void setSetupTime(String SetupTime) {
        this.SetupTime = SetupTime;
    }

}
