package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_SPARE_PART_APPLY.
 */
public class EntitySparePartApply {

    public Integer ID;
    public String ApplyStatus;
    public String QuotationID;
    public String ApplyCompanyCode;
    public String ApplyCompanyID;
    public String ApplyCompanyName;
    public String ApplyContent;
    public String ApplyUserID;
    public String ApplyUserName;
    public String ApplyUserStaffNo;
    public String Telephone;
    public String ApplyTime;
    public String ProgramName;
    public String WorkorderID;
    public String DeviceCode;
    public String Creator;
    public String CreateTime;
    public String CreateIP;
    public String Updater;
    public String UpdateTime;
    public String UpdateIP;
    public String BigCustomerID;
    public String BigCustomerName;
    public String HandlerUser;
    public String HandlerTime;
    public String HandlerTelephone;

    public EntitySparePartApply() {
    }

    public EntitySparePartApply(Integer ID, String ApplyStatus, String QuotationID, String ApplyCompanyCode, String ApplyCompanyID, String ApplyCompanyName, String ApplyContent, String ApplyUserID, String ApplyUserName, String ApplyUserStaffNo, String Telephone, String ApplyTime, String ProgramName, String WorkorderID, String DeviceCode, String Creator, String CreateTime, String CreateIP, String Updater, String UpdateTime, String UpdateIP, String BigCustomerID, String BigCustomerName, String HandlerUser, String HandlerTime, String HandlerTelephone) {
        this.ID = ID;
        this.ApplyStatus = ApplyStatus;
        this.QuotationID = QuotationID;
        this.ApplyCompanyCode = ApplyCompanyCode;
        this.ApplyCompanyID = ApplyCompanyID;
        this.ApplyCompanyName = ApplyCompanyName;
        this.ApplyContent = ApplyContent;
        this.ApplyUserID = ApplyUserID;
        this.ApplyUserName = ApplyUserName;
        this.ApplyUserStaffNo = ApplyUserStaffNo;
        this.Telephone = Telephone;
        this.ApplyTime = ApplyTime;
        this.ProgramName = ProgramName;
        this.WorkorderID = WorkorderID;
        this.DeviceCode = DeviceCode;
        this.Creator = Creator;
        this.CreateTime = CreateTime;
        this.CreateIP = CreateIP;
        this.Updater = Updater;
        this.UpdateTime = UpdateTime;
        this.UpdateIP = UpdateIP;
        this.BigCustomerID = BigCustomerID;
        this.BigCustomerName = BigCustomerName;
        this.HandlerUser = HandlerUser;
        this.HandlerTime = HandlerTime;
        this.HandlerTelephone = HandlerTelephone;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public String getApplyStatus() {
        return ApplyStatus;
    }

    public void setApplyStatus(String ApplyStatus) {
        this.ApplyStatus = ApplyStatus;
    }

    public String getQuotationID() {
        return QuotationID;
    }

    public void setQuotationID(String QuotationID) {
        this.QuotationID = QuotationID;
    }

    public String getApplyCompanyCode() {
        return ApplyCompanyCode;
    }

    public void setApplyCompanyCode(String ApplyCompanyCode) {
        this.ApplyCompanyCode = ApplyCompanyCode;
    }

    public String getApplyCompanyID() {
        return ApplyCompanyID;
    }

    public void setApplyCompanyID(String ApplyCompanyID) {
        this.ApplyCompanyID = ApplyCompanyID;
    }

    public String getApplyCompanyName() {
        return ApplyCompanyName;
    }

    public void setApplyCompanyName(String ApplyCompanyName) {
        this.ApplyCompanyName = ApplyCompanyName;
    }

    public String getApplyContent() {
        return ApplyContent;
    }

    public void setApplyContent(String ApplyContent) {
        this.ApplyContent = ApplyContent;
    }

    public String getApplyUserID() {
        return ApplyUserID;
    }

    public void setApplyUserID(String ApplyUserID) {
        this.ApplyUserID = ApplyUserID;
    }

    public String getApplyUserName() {
        return ApplyUserName;
    }

    public void setApplyUserName(String ApplyUserName) {
        this.ApplyUserName = ApplyUserName;
    }

    public String getApplyUserStaffNo() {
        return ApplyUserStaffNo;
    }

    public void setApplyUserStaffNo(String ApplyUserStaffNo) {
        this.ApplyUserStaffNo = ApplyUserStaffNo;
    }

    public String getTelephone() {
        return Telephone;
    }

    public void setTelephone(String Telephone) {
        this.Telephone = Telephone;
    }

    public String getApplyTime() {
        return ApplyTime;
    }

    public void setApplyTime(String ApplyTime) {
        this.ApplyTime = ApplyTime;
    }

    public String getProgramName() {
        return ProgramName;
    }

    public void setProgramName(String ProgramName) {
        this.ProgramName = ProgramName;
    }

    public String getWorkorderID() {
        return WorkorderID;
    }

    public void setWorkorderID(String WorkorderID) {
        this.WorkorderID = WorkorderID;
    }

    public String getDeviceCode() {
        return DeviceCode;
    }

    public void setDeviceCode(String DeviceCode) {
        this.DeviceCode = DeviceCode;
    }

    public String getCreator() {
        return Creator;
    }

    public void setCreator(String Creator) {
        this.Creator = Creator;
    }

    public String getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    public String getCreateIP() {
        return CreateIP;
    }

    public void setCreateIP(String CreateIP) {
        this.CreateIP = CreateIP;
    }

    public String getUpdater() {
        return Updater;
    }

    public void setUpdater(String Updater) {
        this.Updater = Updater;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

    public String getUpdateIP() {
        return UpdateIP;
    }

    public void setUpdateIP(String UpdateIP) {
        this.UpdateIP = UpdateIP;
    }

    public String getBigCustomerID() {
        return BigCustomerID;
    }

    public void setBigCustomerID(String BigCustomerID) {
        this.BigCustomerID = BigCustomerID;
    }

    public String getBigCustomerName() {
        return BigCustomerName;
    }

    public void setBigCustomerName(String BigCustomerName) {
        this.BigCustomerName = BigCustomerName;
    }

    public String getHandlerUser() {
        return HandlerUser;
    }

    public void setHandlerUser(String HandlerUser) {
        this.HandlerUser = HandlerUser;
    }

    public String getHandlerTime() {
        return HandlerTime;
    }

    public void setHandlerTime(String HandlerTime) {
        this.HandlerTime = HandlerTime;
    }

    public String getHandlerTelephone() {
        return HandlerTelephone;
    }

    public void setHandlerTelephone(String HandlerTelephone) {
        this.HandlerTelephone = HandlerTelephone;
    }

}
