package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_CHECK.
 */
public class EntityCheck {

    public String InnerID;
    public String Add_UserID;
    public String Add_Time;
    public String Add_IP;
    public String Update_UserID;
    public String Update_Time;
    public String Update_IP;
    public String CompleteDate	;
    public String ConfirmUserID;
    public String ConfirmRemark;
    public Integer IsNeedAbarbeitung;
    public String StartLongitude;
    public String StartLatitude;
    public String EndLongitude;
    public String EndLatitude;
    public String CheckDesc;
    public String is_pic_exists;

    public EntityCheck() {
    }

    public EntityCheck(String InnerID, String Add_UserID, String Add_Time, String Add_IP, String Update_UserID, String Update_Time, String Update_IP, String CompleteDate	, String ConfirmUserID, String ConfirmRemark, Integer IsNeedAbarbeitung, String StartLongitude, String StartLatitude, String EndLongitude, String EndLatitude, String CheckDesc, String is_pic_exists) {
        this.InnerID = InnerID;
        this.Add_UserID = Add_UserID;
        this.Add_Time = Add_Time;
        this.Add_IP = Add_IP;
        this.Update_UserID = Update_UserID;
        this.Update_Time = Update_Time;
        this.Update_IP = Update_IP;
        this.CompleteDate	 = CompleteDate	;
        this.ConfirmUserID = ConfirmUserID;
        this.ConfirmRemark = ConfirmRemark;
        this.IsNeedAbarbeitung = IsNeedAbarbeitung;
        this.StartLongitude = StartLongitude;
        this.StartLatitude = StartLatitude;
        this.EndLongitude = EndLongitude;
        this.EndLatitude = EndLatitude;
        this.CheckDesc = CheckDesc;
        this.is_pic_exists = is_pic_exists;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getAdd_UserID() {
        return Add_UserID;
    }

    public void setAdd_UserID(String Add_UserID) {
        this.Add_UserID = Add_UserID;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getAdd_IP() {
        return Add_IP;
    }

    public void setAdd_IP(String Add_IP) {
        this.Add_IP = Add_IP;
    }

    public String getUpdate_UserID() {
        return Update_UserID;
    }

    public void setUpdate_UserID(String Update_UserID) {
        this.Update_UserID = Update_UserID;
    }

    public String getUpdate_Time() {
        return Update_Time;
    }

    public void setUpdate_Time(String Update_Time) {
        this.Update_Time = Update_Time;
    }

    public String getUpdate_IP() {
        return Update_IP;
    }

    public void setUpdate_IP(String Update_IP) {
        this.Update_IP = Update_IP;
    }

    public String getCompleteDate	() {
        return CompleteDate	;
    }

    public void setCompleteDate	(String CompleteDate	) {
        this.CompleteDate	 = CompleteDate	;
    }

    public String getConfirmUserID() {
        return ConfirmUserID;
    }

    public void setConfirmUserID(String ConfirmUserID) {
        this.ConfirmUserID = ConfirmUserID;
    }

    public String getConfirmRemark() {
        return ConfirmRemark;
    }

    public void setConfirmRemark(String ConfirmRemark) {
        this.ConfirmRemark = ConfirmRemark;
    }

    public Integer getIsNeedAbarbeitung() {
        return IsNeedAbarbeitung;
    }

    public void setIsNeedAbarbeitung(Integer IsNeedAbarbeitung) {
        this.IsNeedAbarbeitung = IsNeedAbarbeitung;
    }

    public String getStartLongitude() {
        return StartLongitude;
    }

    public void setStartLongitude(String StartLongitude) {
        this.StartLongitude = StartLongitude;
    }

    public String getStartLatitude() {
        return StartLatitude;
    }

    public void setStartLatitude(String StartLatitude) {
        this.StartLatitude = StartLatitude;
    }

    public String getEndLongitude() {
        return EndLongitude;
    }

    public void setEndLongitude(String EndLongitude) {
        this.EndLongitude = EndLongitude;
    }

    public String getEndLatitude() {
        return EndLatitude;
    }

    public void setEndLatitude(String EndLatitude) {
        this.EndLatitude = EndLatitude;
    }

    public String getCheckDesc() {
        return CheckDesc;
    }

    public void setCheckDesc(String CheckDesc) {
        this.CheckDesc = CheckDesc;
    }

    public String getIs_pic_exists() {
        return is_pic_exists;
    }

    public void setIs_pic_exists(String is_pic_exists) {
        this.is_pic_exists = is_pic_exists;
    }

}
