package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_DEVICE.
 */
public class EntityDevice {

    public String InnerID;
    public String Lift_Address;
    public String Lift_Type;
    public String Lift_Style;
    public String Company_Name;
    public String Company_Address;
    public String Village_Address;
    public String Village_Name;
    public String Village_Group_Num;
    public String Village_Stage_Num;
    public String Device_Num;
    public String Contract_Num;
    public String Specification;
    public String Delivery_Date;
    public String Manufacturer;
    public String Program_Name;
    public String User_Company;
    public String LoginCode;
    public String Longitude;
    public String Latitude;
    public String LastMaintainTime;

    public EntityDevice() {
    }

    public EntityDevice(String InnerID, String Lift_Address, String Lift_Type, String Lift_Style, String Company_Name, String Company_Address, String Village_Address, String Village_Name, String Village_Group_Num, String Village_Stage_Num, String Device_Num, String Contract_Num, String Specification, String Delivery_Date, String Manufacturer, String Program_Name, String User_Company, String LoginCode, String Longitude, String Latitude, String LastMaintainTime) {
        this.InnerID = InnerID;
        this.Lift_Address = Lift_Address;
        this.Lift_Type = Lift_Type;
        this.Lift_Style = Lift_Style;
        this.Company_Name = Company_Name;
        this.Company_Address = Company_Address;
        this.Village_Address = Village_Address;
        this.Village_Name = Village_Name;
        this.Village_Group_Num = Village_Group_Num;
        this.Village_Stage_Num = Village_Stage_Num;
        this.Device_Num = Device_Num;
        this.Contract_Num = Contract_Num;
        this.Specification = Specification;
        this.Delivery_Date = Delivery_Date;
        this.Manufacturer = Manufacturer;
        this.Program_Name = Program_Name;
        this.User_Company = User_Company;
        this.LoginCode = LoginCode;
        this.Longitude = Longitude;
        this.Latitude = Latitude;
        this.LastMaintainTime = LastMaintainTime;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getLift_Address() {
        return Lift_Address;
    }

    public void setLift_Address(String Lift_Address) {
        this.Lift_Address = Lift_Address;
    }

    public String getLift_Type() {
        return Lift_Type;
    }

    public void setLift_Type(String Lift_Type) {
        this.Lift_Type = Lift_Type;
    }

    public String getLift_Style() {
        return Lift_Style;
    }

    public void setLift_Style(String Lift_Style) {
        this.Lift_Style = Lift_Style;
    }

    public String getCompany_Name() {
        return Company_Name;
    }

    public void setCompany_Name(String Company_Name) {
        this.Company_Name = Company_Name;
    }

    public String getCompany_Address() {
        return Company_Address;
    }

    public void setCompany_Address(String Company_Address) {
        this.Company_Address = Company_Address;
    }

    public String getVillage_Address() {
        return Village_Address;
    }

    public void setVillage_Address(String Village_Address) {
        this.Village_Address = Village_Address;
    }

    public String getVillage_Name() {
        return Village_Name;
    }

    public void setVillage_Name(String Village_Name) {
        this.Village_Name = Village_Name;
    }

    public String getVillage_Group_Num() {
        return Village_Group_Num;
    }

    public void setVillage_Group_Num(String Village_Group_Num) {
        this.Village_Group_Num = Village_Group_Num;
    }

    public String getVillage_Stage_Num() {
        return Village_Stage_Num;
    }

    public void setVillage_Stage_Num(String Village_Stage_Num) {
        this.Village_Stage_Num = Village_Stage_Num;
    }

    public String getDevice_Num() {
        return Device_Num;
    }

    public void setDevice_Num(String Device_Num) {
        this.Device_Num = Device_Num;
    }

    public String getContract_Num() {
        return Contract_Num;
    }

    public void setContract_Num(String Contract_Num) {
        this.Contract_Num = Contract_Num;
    }

    public String getSpecification() {
        return Specification;
    }

    public void setSpecification(String Specification) {
        this.Specification = Specification;
    }

    public String getDelivery_Date() {
        return Delivery_Date;
    }

    public void setDelivery_Date(String Delivery_Date) {
        this.Delivery_Date = Delivery_Date;
    }

    public String getManufacturer() {
        return Manufacturer;
    }

    public void setManufacturer(String Manufacturer) {
        this.Manufacturer = Manufacturer;
    }

    public String getProgram_Name() {
        return Program_Name;
    }

    public void setProgram_Name(String Program_Name) {
        this.Program_Name = Program_Name;
    }

    public String getUser_Company() {
        return User_Company;
    }

    public void setUser_Company(String User_Company) {
        this.User_Company = User_Company;
    }

    public String getLoginCode() {
        return LoginCode;
    }

    public void setLoginCode(String LoginCode) {
        this.LoginCode = LoginCode;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    public String getLastMaintainTime() {
        return LastMaintainTime;
    }

    public void setLastMaintainTime(String LastMaintainTime) {
        this.LastMaintainTime = LastMaintainTime;
    }

}
