package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_ASSIST_WORKER.
 */
public class EntityAssistWorker {

    public String UserID;
    public Integer AssistStatus;
    public String StaffNo;
    public String Name;
    public String Telephone;

    public EntityAssistWorker() {
    }

    public EntityAssistWorker(String UserID, Integer AssistStatus, String StaffNo, String Name, String Telephone) {
        this.UserID = UserID;
        this.AssistStatus = AssistStatus;
        this.StaffNo = StaffNo;
        this.Name = Name;
        this.Telephone = Telephone;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public Integer getAssistStatus() {
        return AssistStatus;
    }

    public void setAssistStatus(Integer AssistStatus) {
        this.AssistStatus = AssistStatus;
    }

    public String getStaffNo() {
        return StaffNo;
    }

    public void setStaffNo(String StaffNo) {
        this.StaffNo = StaffNo;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getTelephone() {
        return Telephone;
    }

    public void setTelephone(String Telephone) {
        this.Telephone = Telephone;
    }

}
