package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_BIG_CUSTOMER.
 */
public class EntityBigCustomer {

    public Integer ID;
    public String LsNo;
    public String BitCustomerName;
    public Integer COOP_Status;
    public String Remark;

    public EntityBigCustomer() {
    }

    public EntityBigCustomer(Integer ID, String LsNo, String BitCustomerName, Integer COOP_Status, String Remark) {
        this.ID = ID;
        this.LsNo = LsNo;
        this.BitCustomerName = BitCustomerName;
        this.COOP_Status = COOP_Status;
        this.Remark = Remark;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

    public String getLsNo() {
        return LsNo;
    }

    public void setLsNo(String LsNo) {
        this.LsNo = LsNo;
    }

    public String getBitCustomerName() {
        return BitCustomerName;
    }

    public void setBitCustomerName(String BitCustomerName) {
        this.BitCustomerName = BitCustomerName;
    }

    public Integer getCOOP_Status() {
        return COOP_Status;
    }

    public void setCOOP_Status(Integer COOP_Status) {
        this.COOP_Status = COOP_Status;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

}
