package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_WORKORDER.
 */
public class EntityWorkorder {

    public String InnerID;
    public String Company_Num;
    public String Device_Num;
    public String EventSource;
    public String ForeignID;
    public String Remark;
    public String SolutionInfo;
    public Integer Status;
    public Integer Type;
    public String ControlType;
    public String Add_Time;
    public String Village_Name;
    public String Village_Group_Num;
    public String Village_Stage_Num;
    public String ChargeUserID;
    public String ChargeUserName;
    public String ChargeUserPhone;
    public String StartTime;
    public String EndTime;
    public Integer OrderPause;
    public String ProvisionMaintainTime;
    public String StartType;
    public String CompleteDate;
    public String IsNeedAbarbeitung;
    public String Program_Name;
    public String LastSeasonMaintain;
    public String LastHalfYearMaintain;
    public String MaintainType;
    public String ResultDesc;
    public String ResultType;
    public String is_pic_exists;

    public EntityWorkorder() {
    }

    public EntityWorkorder(String InnerID, String Company_Num, String Device_Num, String EventSource, String ForeignID, String Remark, String SolutionInfo, Integer Status, Integer Type, String ControlType, String Add_Time, String Village_Name, String Village_Group_Num, String Village_Stage_Num, String ChargeUserID, String ChargeUserName, String ChargeUserPhone, String StartTime, String EndTime, Integer OrderPause, String ProvisionMaintainTime, String StartType, String CompleteDate, String IsNeedAbarbeitung, String Program_Name, String LastSeasonMaintain, String LastHalfYearMaintain, String MaintainType, String ResultDesc, String ResultType, String is_pic_exists) {
        this.InnerID = InnerID;
        this.Company_Num = Company_Num;
        this.Device_Num = Device_Num;
        this.EventSource = EventSource;
        this.ForeignID = ForeignID;
        this.Remark = Remark;
        this.SolutionInfo = SolutionInfo;
        this.Status = Status;
        this.Type = Type;
        this.ControlType = ControlType;
        this.Add_Time = Add_Time;
        this.Village_Name = Village_Name;
        this.Village_Group_Num = Village_Group_Num;
        this.Village_Stage_Num = Village_Stage_Num;
        this.ChargeUserID = ChargeUserID;
        this.ChargeUserName = ChargeUserName;
        this.ChargeUserPhone = ChargeUserPhone;
        this.StartTime = StartTime;
        this.EndTime = EndTime;
        this.OrderPause = OrderPause;
        this.ProvisionMaintainTime = ProvisionMaintainTime;
        this.StartType = StartType;
        this.CompleteDate = CompleteDate;
        this.IsNeedAbarbeitung = IsNeedAbarbeitung;
        this.Program_Name = Program_Name;
        this.LastSeasonMaintain = LastSeasonMaintain;
        this.LastHalfYearMaintain = LastHalfYearMaintain;
        this.MaintainType = MaintainType;
        this.ResultDesc = ResultDesc;
        this.ResultType = ResultType;
        this.is_pic_exists = is_pic_exists;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getCompany_Num() {
        return Company_Num;
    }

    public void setCompany_Num(String Company_Num) {
        this.Company_Num = Company_Num;
    }

    public String getDevice_Num() {
        return Device_Num;
    }

    public void setDevice_Num(String Device_Num) {
        this.Device_Num = Device_Num;
    }

    public String getEventSource() {
        return EventSource;
    }

    public void setEventSource(String EventSource) {
        this.EventSource = EventSource;
    }

    public String getForeignID() {
        return ForeignID;
    }

    public void setForeignID(String ForeignID) {
        this.ForeignID = ForeignID;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getSolutionInfo() {
        return SolutionInfo;
    }

    public void setSolutionInfo(String SolutionInfo) {
        this.SolutionInfo = SolutionInfo;
    }

    public Integer getStatus() {
        return Status;
    }

    public void setStatus(Integer Status) {
        this.Status = Status;
    }

    public Integer getType() {
        return Type;
    }

    public void setType(Integer Type) {
        this.Type = Type;
    }

    public String getControlType() {
        return ControlType;
    }

    public void setControlType(String ControlType) {
        this.ControlType = ControlType;
    }

    public String getAdd_Time() {
        return Add_Time;
    }

    public void setAdd_Time(String Add_Time) {
        this.Add_Time = Add_Time;
    }

    public String getVillage_Name() {
        return Village_Name;
    }

    public void setVillage_Name(String Village_Name) {
        this.Village_Name = Village_Name;
    }

    public String getVillage_Group_Num() {
        return Village_Group_Num;
    }

    public void setVillage_Group_Num(String Village_Group_Num) {
        this.Village_Group_Num = Village_Group_Num;
    }

    public String getVillage_Stage_Num() {
        return Village_Stage_Num;
    }

    public void setVillage_Stage_Num(String Village_Stage_Num) {
        this.Village_Stage_Num = Village_Stage_Num;
    }

    public String getChargeUserID() {
        return ChargeUserID;
    }

    public void setChargeUserID(String ChargeUserID) {
        this.ChargeUserID = ChargeUserID;
    }

    public String getChargeUserName() {
        return ChargeUserName;
    }

    public void setChargeUserName(String ChargeUserName) {
        this.ChargeUserName = ChargeUserName;
    }

    public String getChargeUserPhone() {
        return ChargeUserPhone;
    }

    public void setChargeUserPhone(String ChargeUserPhone) {
        this.ChargeUserPhone = ChargeUserPhone;
    }

    public String getStartTime() {
        return StartTime;
    }

    public void setStartTime(String StartTime) {
        this.StartTime = StartTime;
    }

    public String getEndTime() {
        return EndTime;
    }

    public void setEndTime(String EndTime) {
        this.EndTime = EndTime;
    }

    public Integer getOrderPause() {
        return OrderPause;
    }

    public void setOrderPause(Integer OrderPause) {
        this.OrderPause = OrderPause;
    }

    public String getProvisionMaintainTime() {
        return ProvisionMaintainTime;
    }

    public void setProvisionMaintainTime(String ProvisionMaintainTime) {
        this.ProvisionMaintainTime = ProvisionMaintainTime;
    }

    public String getStartType() {
        return StartType;
    }

    public void setStartType(String StartType) {
        this.StartType = StartType;
    }

    public String getCompleteDate() {
        return CompleteDate;
    }

    public void setCompleteDate(String CompleteDate) {
        this.CompleteDate = CompleteDate;
    }

    public String getIsNeedAbarbeitung() {
        return IsNeedAbarbeitung;
    }

    public void setIsNeedAbarbeitung(String IsNeedAbarbeitung) {
        this.IsNeedAbarbeitung = IsNeedAbarbeitung;
    }

    public String getProgram_Name() {
        return Program_Name;
    }

    public void setProgram_Name(String Program_Name) {
        this.Program_Name = Program_Name;
    }

    public String getLastSeasonMaintain() {
        return LastSeasonMaintain;
    }

    public void setLastSeasonMaintain(String LastSeasonMaintain) {
        this.LastSeasonMaintain = LastSeasonMaintain;
    }

    public String getLastHalfYearMaintain() {
        return LastHalfYearMaintain;
    }

    public void setLastHalfYearMaintain(String LastHalfYearMaintain) {
        this.LastHalfYearMaintain = LastHalfYearMaintain;
    }

    public String getMaintainType() {
        return MaintainType;
    }

    public void setMaintainType(String MaintainType) {
        this.MaintainType = MaintainType;
    }

    public String getResultDesc() {
        return ResultDesc;
    }

    public void setResultDesc(String ResultDesc) {
        this.ResultDesc = ResultDesc;
    }

    public String getResultType() {
        return ResultType;
    }

    public void setResultType(String ResultType) {
        this.ResultType = ResultType;
    }

    public String getIs_pic_exists() {
        return is_pic_exists;
    }

    public void setIs_pic_exists(String is_pic_exists) {
        this.is_pic_exists = is_pic_exists;
    }

}
