package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_WORKORDER_PUSH_LOG.
 */
public class EntityWorkorderPushLog {

    public String Telephone;
    public String UserName;
    public String PushResult;
    public String PushTime;

    public EntityWorkorderPushLog() {
    }

    public EntityWorkorderPushLog(String Telephone, String UserName, String PushResult, String PushTime) {
        this.Telephone = Telephone;
        this.UserName = UserName;
        this.PushResult = PushResult;
        this.PushTime = PushTime;
    }

    public String getTelephone() {
        return Telephone;
    }

    public void setTelephone(String Telephone) {
        this.Telephone = Telephone;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getPushResult() {
        return PushResult;
    }

    public void setPushResult(String PushResult) {
        this.PushResult = PushResult;
    }

    public String getPushTime() {
        return PushTime;
    }

    public void setPushTime(String PushTime) {
        this.PushTime = PushTime;
    }

}
