package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_PAUSE_LOG.
 */
public class EntityPauseLog {

    public String InnerID;
    public String WorkorderID;
    public String OccurTime;
    public String UserID;
    public String FromPauseStatus;
    public String TargetPauseStatus;
    public String AdminCheck;
    public String CheckTime;
    public String Remark;
    public String CheckUserID;
    public String UserName;
    public String CheckUserName;
    public String CheckUserStaffID;

    public EntityPauseLog() {
    }

    public EntityPauseLog(String InnerID, String WorkorderID, String OccurTime, String UserID, String FromPauseStatus, String TargetPauseStatus, String AdminCheck, String CheckTime, String Remark, String CheckUserID, String UserName, String CheckUserName, String CheckUserStaffID) {
        this.InnerID = InnerID;
        this.WorkorderID = WorkorderID;
        this.OccurTime = OccurTime;
        this.UserID = UserID;
        this.FromPauseStatus = FromPauseStatus;
        this.TargetPauseStatus = TargetPauseStatus;
        this.AdminCheck = AdminCheck;
        this.CheckTime = CheckTime;
        this.Remark = Remark;
        this.CheckUserID = CheckUserID;
        this.UserName = UserName;
        this.CheckUserName = CheckUserName;
        this.CheckUserStaffID = CheckUserStaffID;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getWorkorderID() {
        return WorkorderID;
    }

    public void setWorkorderID(String WorkorderID) {
        this.WorkorderID = WorkorderID;
    }

    public String getOccurTime() {
        return OccurTime;
    }

    public void setOccurTime(String OccurTime) {
        this.OccurTime = OccurTime;
    }

    public String getUserID() {
        return UserID;
    }

    public void setUserID(String UserID) {
        this.UserID = UserID;
    }

    public String getFromPauseStatus() {
        return FromPauseStatus;
    }

    public void setFromPauseStatus(String FromPauseStatus) {
        this.FromPauseStatus = FromPauseStatus;
    }

    public String getTargetPauseStatus() {
        return TargetPauseStatus;
    }

    public void setTargetPauseStatus(String TargetPauseStatus) {
        this.TargetPauseStatus = TargetPauseStatus;
    }

    public String getAdminCheck() {
        return AdminCheck;
    }

    public void setAdminCheck(String AdminCheck) {
        this.AdminCheck = AdminCheck;
    }

    public String getCheckTime() {
        return CheckTime;
    }

    public void setCheckTime(String CheckTime) {
        this.CheckTime = CheckTime;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getCheckUserID() {
        return CheckUserID;
    }

    public void setCheckUserID(String CheckUserID) {
        this.CheckUserID = CheckUserID;
    }

    public String getUserName() {
        return UserName;
    }

    public void setUserName(String UserName) {
        this.UserName = UserName;
    }

    public String getCheckUserName() {
        return CheckUserName;
    }

    public void setCheckUserName(String CheckUserName) {
        this.CheckUserName = CheckUserName;
    }

    public String getCheckUserStaffID() {
        return CheckUserStaffID;
    }

    public void setCheckUserStaffID(String CheckUserStaffID) {
        this.CheckUserStaffID = CheckUserStaffID;
    }

}
