package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_SPARE_PART_APPLY_DATA.
 */
public class EntitySparePartApplyData {

    public String App_Quotation_ID;
    public String Part_Name;
    public String Draw_Code;
    public String Code;
    public String Quantity;
    public String Description;
    public String CreateTime;
    public String Creator;
    public String CreateIP;
    public String UpdateTime;
    public String Updater;
    public String UpdateIP;
    public Integer ID;

    public EntitySparePartApplyData() {
    }

    public EntitySparePartApplyData(String App_Quotation_ID, String Part_Name, String Draw_Code, String Code, String Quantity, String Description, String CreateTime, String Creator, String CreateIP, String UpdateTime, String Updater, String UpdateIP, Integer ID) {
        this.App_Quotation_ID = App_Quotation_ID;
        this.Part_Name = Part_Name;
        this.Draw_Code = Draw_Code;
        this.Code = Code;
        this.Quantity = Quantity;
        this.Description = Description;
        this.CreateTime = CreateTime;
        this.Creator = Creator;
        this.CreateIP = CreateIP;
        this.UpdateTime = UpdateTime;
        this.Updater = Updater;
        this.UpdateIP = UpdateIP;
        this.ID = ID;
    }

    public String getApp_Quotation_ID() {
        return App_Quotation_ID;
    }

    public void setApp_Quotation_ID(String App_Quotation_ID) {
        this.App_Quotation_ID = App_Quotation_ID;
    }

    public String getPart_Name() {
        return Part_Name;
    }

    public void setPart_Name(String Part_Name) {
        this.Part_Name = Part_Name;
    }

    public String getDraw_Code() {
        return Draw_Code;
    }

    public void setDraw_Code(String Draw_Code) {
        this.Draw_Code = Draw_Code;
    }

    public String getCode() {
        return Code;
    }

    public void setCode(String Code) {
        this.Code = Code;
    }

    public String getQuantity() {
        return Quantity;
    }

    public void setQuantity(String Quantity) {
        this.Quantity = Quantity;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getCreateTime() {
        return CreateTime;
    }

    public void setCreateTime(String CreateTime) {
        this.CreateTime = CreateTime;
    }

    public String getCreator() {
        return Creator;
    }

    public void setCreator(String Creator) {
        this.Creator = Creator;
    }

    public String getCreateIP() {
        return CreateIP;
    }

    public void setCreateIP(String CreateIP) {
        this.CreateIP = CreateIP;
    }

    public String getUpdateTime() {
        return UpdateTime;
    }

    public void setUpdateTime(String UpdateTime) {
        this.UpdateTime = UpdateTime;
    }

    public String getUpdater() {
        return Updater;
    }

    public void setUpdater(String Updater) {
        this.Updater = Updater;
    }

    public String getUpdateIP() {
        return UpdateIP;
    }

    public void setUpdateIP(String UpdateIP) {
        this.UpdateIP = UpdateIP;
    }

    public Integer getID() {
        return ID;
    }

    public void setID(Integer ID) {
        this.ID = ID;
    }

}
