package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_FACTORY_CODE.
 */
public class EntityFactoryCode {

    public String InnerID;
    public String CompanyName;
    public String CompanyCode;
    public String CompanyIndex;

    public EntityFactoryCode() {
    }

    public EntityFactoryCode(String InnerID, String CompanyName, String CompanyCode, String CompanyIndex) {
        this.InnerID = InnerID;
        this.CompanyName = CompanyName;
        this.CompanyCode = CompanyCode;
        this.CompanyIndex = CompanyIndex;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getCompanyName() {
        return CompanyName;
    }

    public void setCompanyName(String CompanyName) {
        this.CompanyName = CompanyName;
    }

    public String getCompanyCode() {
        return CompanyCode;
    }

    public void setCompanyCode(String CompanyCode) {
        this.CompanyCode = CompanyCode;
    }

    public String getCompanyIndex() {
        return CompanyIndex;
    }

    public void setCompanyIndex(String CompanyIndex) {
        this.CompanyIndex = CompanyIndex;
    }

}
