package com.sjec.rcms.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENTITY_VILLAGE.
 */
public class EntityVillage {

    public String InnerID;
    public String Village_ProID;
    public String Village_ProName;
    public String Village_CityID;
    public String Village_CityName;
    public String Village_Name;
    public String Address;
    public String Remark;

    public EntityVillage() {
    }

    public EntityVillage(String InnerID, String Village_ProID, String Village_ProName, String Village_CityID, String Village_CityName, String Village_Name, String Address, String Remark) {
        this.InnerID = InnerID;
        this.Village_ProID = Village_ProID;
        this.Village_ProName = Village_ProName;
        this.Village_CityID = Village_CityID;
        this.Village_CityName = Village_CityName;
        this.Village_Name = Village_Name;
        this.Address = Address;
        this.Remark = Remark;
    }

    public String getInnerID() {
        return InnerID;
    }

    public void setInnerID(String InnerID) {
        this.InnerID = InnerID;
    }

    public String getVillage_ProID() {
        return Village_ProID;
    }

    public void setVillage_ProID(String Village_ProID) {
        this.Village_ProID = Village_ProID;
    }

    public String getVillage_ProName() {
        return Village_ProName;
    }

    public void setVillage_ProName(String Village_ProName) {
        this.Village_ProName = Village_ProName;
    }

    public String getVillage_CityID() {
        return Village_CityID;
    }

    public void setVillage_CityID(String Village_CityID) {
        this.Village_CityID = Village_CityID;
    }

    public String getVillage_CityName() {
        return Village_CityName;
    }

    public void setVillage_CityName(String Village_CityName) {
        this.Village_CityName = Village_CityName;
    }

    public String getVillage_Name() {
        return Village_Name;
    }

    public void setVillage_Name(String Village_Name) {
        this.Village_Name = Village_Name;
    }

    public String getAddress() {
        return Address;
    }

    public void setAddress(String Address) {
        this.Address = Address;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

}
